package dialect

import (
	"database/sql"
	"fmt"
	"reflect"
	"strings"

	"github.com/shrek82/jorm/model"
)

type oracle struct{}

func (d *oracle) DataTypeOf(typ reflect.Type) string {
	switch typ.Kind() {
	case reflect.Bool:
		return "number(1)"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uintptr:
		return "number(10)"
	case reflect.Int64, reflect.Uint64:
		return "number(19)"
	case reflect.Float32, reflect.Float64:
		return "binary_double"
	case reflect.String:
		return "varchar2(255)"
	case reflect.Struct:
		if typ.Name() == "Time" {
			return "timestamp"
		}
	}
	panic(fmt.Sprintf("invalid sql type %s (%s)", typ.Name(), typ.Kind()))
}

func (d *oracle) Quote(name string) string {
	return fmt.Sprintf("\"%s\"", strings.ToUpper(name))
}

func (d *oracle) InsertSQL(table string, columns []string) (string, []any) {
	var placeholders []string
	for i := range columns {
		placeholders = append(placeholders, fmt.Sprintf(":%d", i+1))
	}
	sql := fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s)",
		d.Quote(table),
		strings.Join(columns, ", "),
		strings.Join(placeholders, ", "),
	)
	return sql, nil
}

func (d *oracle) CreateTableSQL(m *model.Model) (string, []any) {
	var columns []string
	for _, field := range m.Fields {
		column := fmt.Sprintf("%s %s", d.Quote(field.Column), d.DataTypeOf(field.Type))
		if field.IsPK {
			column += " PRIMARY KEY"
		}
		if field.IsAuto {
			column += " GENERATED BY DEFAULT AS IDENTITY"
		}
		columns = append(columns, column)
	}
	sql := fmt.Sprintf("CREATE TABLE %s (%s)", d.Quote(m.TableName), strings.Join(columns, ", "))
	return sql, nil
}

func (d *oracle) HasTableSQL(tableName string) (string, []any) {
	return "SELECT count(*) FROM user_tables WHERE table_name = UPPER(:1)", []any{tableName}
}

func (d *oracle) BatchInsertSQL(table string, columns []string, count int) (string, []any) {
	var rowPlaceholders []string
	argIndex := 1
	for i := 0; i < count; i++ {
		var placeholders []string
		for range columns {
			placeholders = append(placeholders, fmt.Sprintf(":%d", argIndex))
			argIndex++
		}
		rowPlaceholders = append(rowPlaceholders, "("+strings.Join(placeholders, ", ")+")")
	}

	sql := fmt.Sprintf("INSERT INTO %s (%s) VALUES %s",
		d.Quote(table),
		strings.Join(columns, ", "),
		strings.Join(rowPlaceholders, ", "),
	)
	return sql, nil
}

func (d *oracle) Placeholder(index int) string {
	return fmt.Sprintf(":%d", index)
}

func (d *oracle) GetColumnsSQL(tableName string) (string, []any) {
	return "SELECT column_name FROM user_tab_columns WHERE table_name = UPPER(:1)", []any{tableName}
}

func (d *oracle) AddColumnSQL(tableName string, field *model.Field) (string, []any) {
	sql := fmt.Sprintf("ALTER TABLE %s ADD (%s %s)",
		d.Quote(tableName),
		d.Quote(field.Column),
		d.DataTypeOf(field.Type),
	)
	return sql, nil
}

func (d *oracle) ModifyColumnSQL(tableName string, field *model.Field) (string, []any) {
	sql := fmt.Sprintf("ALTER TABLE %s MODIFY (%s %s)",
		d.Quote(tableName),
		d.Quote(field.Column),
		d.DataTypeOf(field.Type),
	)
	return sql, nil
}

func (d *oracle) ParseColumns(rows *sql.Rows) ([]string, error) {
	var columns []string
	for rows.Next() {
		var colName string
		if err := rows.Scan(&colName); err != nil {
			return nil, err
		}
		columns = append(columns, strings.ToLower(colName))
	}
	return columns, nil
}
